apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: r8lwk5je9-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:d9fc5166ca1b1b1e24485f7f0ba4199761e047ca@sha256:262a212b09db001408d700a6ad76323f1cadad8e38e894672268ee387dce5c82
          name: container-image
